notebooks:

	@cd tutorials; \
	python tools/nb_to_doc.py basic_usage; \
	python tools/nb_to_doc.py thunder_context; \
	python tools/nb_to_doc.py input_formats; \
	python tools/nb_to_doc.py images; \
	python tools/nb_to_doc.py series; \
	python tools/nb_to_doc.py clustering; \
	python tools/nb_to_doc.py factorization; \
	python tools/nb_to_doc.py regression; \
	python tools/nb_to_doc.py multi_index; \
	python tools/nb_to_doc.py image_registration;